#!/usr/bin/env python3
"""
Nav2 Navigation Stack — Include-Only — vf_robot_bringup
═══════════════════════════════════════════════════════

Purpose
-------
Launches the full Nav2 navigation pipeline:
controller, planner, smoother, behaviors, BT navigator,
waypoint follower, velocity smoother, and collision monitor.

Provides end-to-end command flow from path planning to robot motion.

This file is NOT standalone. It is included by:
  • bringup_launch.py

Arguments
---------
  params_file    : composed Nav2 parameters YAML (required)
                   Generated by bringup_launch.py → compose_params.py.
  use_sim_time   : true | false (default: true)

Inherited Configuration
-----------------------
  controller     : passed from bringup_launch.py via launch_arguments
                   (NOT declared here — do not set when including this file)
                   Used internally to select cmd_vel routing for vf_passive mode.

Command Flow (cmd_vel pipeline)
------------------------------
  controller_server   →  cmd_vel_nav
                            ↓
  velocity_smoother   →  cmd_vel_smoothed
                            ↓
  collision_monitor   →  cmd_vel
                            ↓
  robot driver / Gazebo

  • controller_server output is remapped from "cmd_vel" → "cmd_vel_nav"
  • collision_monitor publishes the FINAL command to "cmd_vel"
  • behavior_server bypasses this chain and writes directly to /cmd_vel

Special Behavior
----------------
  vf_passive mode:
    Controller output is redirected to a dummy topic to prevent
    zero-velocity commands from overriding the Python sidecar.

Nodes Started
-------------
  controller_server       : local planner (FollowPath plugin)
  planner_server          : global planner
  smoother_server         : path smoothing (global path)
  behavior_server         : recovery behaviors (direct /cmd_vel)
  bt_navigator            : behavior tree execution
  waypoint_follower       : waypoint execution
  velocity_smoother       : cmd_vel filtering/smoothing
  collision_monitor       : safety gate before robot
  lifecycle_manager       : autostarts all nodes

Lifecycle Order
---------------
  controller_server → smoother_server → planner_server →
  behavior_server → bt_navigator → waypoint_follower →
  velocity_smoother → collision_monitor

  Order matters due to costmap and topic dependencies.

Configuration Source
--------------------
  All node parameters are loaded from params_file, generated by
  bringup_launch.py (compose_params step).

Notes
-----
  • velocity_smoother operates on cmd_vel (not path)
  • smoother_server operates on planned paths (not cmd_vel)
  • collision_monitor topic wiring is defined in YAML, not remaps
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node


def generate_launch_description():
    params_file = LaunchConfiguration("params_file")
    use_sim_time = LaunchConfiguration("use_sim_time")
    controller = LaunchConfiguration("controller")

    # Any controller whose C++ plugin returns zero twist (PASSIVE mode) would
    # otherwise publish those zeros to cmd_vel_nav at ~20 Hz, racing the
    # imitation sidecar and getting smoothed to ~0. Route the C++ output to a
    # dead topic so only the Python sidecar reaches the smoother.
    #   - vf_imitationwt → VFMode::PASSIVE (current)
    #   - vf_passive     → legacy alias kept for backward compatibility
    cmd_vel_remap = PythonExpression(
        [
            "'cmd_vel_nav_unused' if '",
            controller,
            "' in ('vf_passive', 'vf_imitationwt') else 'cmd_vel_nav'",
        ]
    )

    # ── controller_server ───────────────────────────────────────────────
    # Owns the local controller plugin (FollowPath) — whichever one the
    # composed params file specifies. Publishes velocity commands to
    # cmd_vel_nav (remapped from the default cmd_vel) so they flow
    # through the smoother/collision_monitor chain.
    controller_server = Node(
        package="nav2_controller",
        executable="controller_server",
        name="controller_server",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
        remappings=[
            ("cmd_vel", cmd_vel_remap),
        ],
    )

    # ── planner_server ──────────────────────────────────────────────────
    planner_server = Node(
        package="nav2_planner",
        executable="planner_server",
        name="planner_server",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── smoother_server ─────────────────────────────────────────────────
    # Post-planner path smoother (runs on the GLOBAL path, not cmd_vel).
    # Don't confuse this with velocity_smoother below — different node,
    # different purpose.
    smoother_server = Node(
        package="nav2_smoother",
        executable="smoother_server",
        name="smoother_server",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── behavior_server ─────────────────────────────────────────────────
    # Recovery behaviors: spin, backup, drive_on_heading, wait, assisted_teleop.
    # NOTE: behavior_server publishes DIRECTLY to /cmd_vel, bypassing the
    # smoother/collision_monitor chain. This is intentional in Nav2 —
    # recoveries need to be able to move the robot even if the main
    # controller cmd_vel chain is stuck. Just be aware of it.
    behavior_server = Node(
        package="nav2_behaviors",
        executable="behavior_server",
        name="behavior_server",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── bt_navigator ────────────────────────────────────────────────────
    bt_navigator = Node(
        package="nav2_bt_navigator",
        executable="bt_navigator",
        name="bt_navigator",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── waypoint_follower ───────────────────────────────────────────────
    waypoint_follower = Node(
        package="nav2_waypoint_follower",
        executable="waypoint_follower",
        name="waypoint_follower",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── velocity_smoother ───────────────────────────────────────────────
    # Reads cmd_vel_nav (from controller), publishes cmd_vel_smoothed
    # (to collision_monitor). The remaps below rename the node's default
    # topics to match this chain.
    velocity_smoother = Node(
        package="nav2_velocity_smoother",
        executable="velocity_smoother",
        name="velocity_smoother",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
        remappings=[
            ("cmd_vel", "cmd_vel_nav"),  # input
            ("cmd_vel_smoothed", "cmd_vel_smoothed"),  # output (explicit)
        ],
    )

    # ── collision_monitor ───────────────────────────────────────────────
    # Safety gate between velocity_smoother and the robot. Reads
    # cmd_vel_smoothed, watches the local costmap, and passes through
    # to cmd_vel — but will clamp or stop the command if a collision
    # is imminent. The cmd_vel_in_topic / cmd_vel_out_topic wiring is
    # set in nav2_base.yaml under collision_monitor.ros__parameters.
    collision_monitor = Node(
        package="nav2_collision_monitor",
        executable="collision_monitor",
        name="collision_monitor",
        output="screen",
        respawn=True,
        respawn_delay=2.0,
        parameters=[params_file, {"use_sim_time": use_sim_time}],
    )

    # ── lifecycle_manager ───────────────────────────────────────────────
    # Activates every Nav2 node in the order listed below. Order matters
    # for dependency reasons:
    #   1. controller_server         (owns local costmap)
    #   2. smoother_server           (post-plan smoothing)
    #   3. planner_server            (owns global costmap)
    #   4. behavior_server           (uses local costmap topic)
    #   5. bt_navigator              (orchestrates everyone above)
    #   6. waypoint_follower         (uses bt_navigator action)
    #   7. velocity_smoother         (consumes controller output)
    #   8. collision_monitor         (final gate before robot)
    lifecycle_manager_navigation = Node(
        package="nav2_lifecycle_manager",
        executable="lifecycle_manager",
        name="lifecycle_manager_navigation",
        output="screen",
        parameters=[
            {
                "use_sim_time": use_sim_time,
                "autostart": True,
                "node_names": [
                    "controller_server",
                    "smoother_server",
                    "planner_server",
                    "behavior_server",
                    "bt_navigator",
                    "waypoint_follower",
                    "velocity_smoother",
                    "collision_monitor",
                ],
            }
        ],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument(
                "params_file", description="Composed Nav2 params YAML"
            ),
            DeclareLaunchArgument("use_sim_time", default_value="true"),
            controller_server,
            planner_server,
            smoother_server,
            behavior_server,
            bt_navigator,
            waypoint_follower,
            velocity_smoother,
            collision_monitor,
            lifecycle_manager_navigation,
        ]
    )
